import Gym from "./srcImages/gym.jpg"
import Beds from './srcImages/beds.jpg'
import EvenHall from "./srcImages/event.jpg"
import Pool from "./srcImages/pool.jpg"
import Standard from './srcImages/standard.jpg'
import Premium from './srcImages/premium.jpg'
import Medium from './srcImages/medium.jpg'
import Trophy from './srcImages/trophy.png'
import Stars from './srcImages/stars.svg'
import Wifi from './srcImages/wifi.svg'
import Clock from './srcImages/clock.png'
import Iron from './srcImages/ironing.png'
import Laundry  from './srcImages/laundry.png'
import Parking from './srcImages/parking.png'
import Breakfast from './srcImages/breakfast.png'
import Thirdbday from './srcImages/ThirdBday.jpeg'
import Thirdeven from './srcImages/ThirdEventHall.jpeg'
import ThirdwedHall from "./srcImages/ThirdwedHall.jpeg"
import fGym from "./srcImages/featureGym.jpeg"
import fSpa from "./srcImages/FeatureSpa.jpeg"
import fPool from "./srcImages/featurePool.jpeg"
export {Gym,Thirdbday, ThirdwedHall, Thirdeven, fGym, fSpa, fPool, Beds, EvenHall, Pool, Standard, Medium, Premium, Trophy, Stars, Wifi, Breakfast, Iron, Clock, Laundry, Parking}